.markdownlint-cli2.yaml, alerts/AggregatedAPIErrors.md, alerts/ClusterOperatorDegraded.md, alerts/ClusterOperatorDown.md, alerts/KubeDeploymentReplicasMismatch.md, alerts/KubeJobFailed.md, alerts/KubeNodeNotReady.md, alerts/KubePodNotReady.md, alerts/NodeFilesystemFillingUP.md, alerts/etcMemberDown.md, alerts/etcdBackendQuotaLowSpace.md, example.md
Here are 10 OCP alert runbook that could be open-sourced as an initial move.
Should probably be reviewed from SREs and product team. 
The first reference is the original runbook
The focus should hereby lie on:
The standardized structure of Meaning, Impact, Diagnosis, Mitigation, Reference.
Including some explanations about the implications to the infrastructure for educational purposes. 
Every step/command has explanations of what is happening.
Reading external links should only provide additional information and not be essential for resolving the issue.
=> OSD-6239: initial runbooks

alerts/HighlyAvailableWorkloadIncorrectlySpread.md
Add runbook for the new HighlyAvailableWorkloadIncorrectlySpread alert,
alerting on highly-available workloads incorrectly spread between
multiple nodes.
/cc @simonpasquier @jan--f @fpetkovski
=> Bug 1974832: Add runbook to HighlyAvailableWorkloadIncorrectlySpread

alerts/HighlyAvailableWorkloadIncorrectlySpread.md
Remove mentions of the node labels since the alert doesn't report it
anymore.
Ref: https://github.com/openshift/cluster-monitoring-operator/pull/1262
=> Fix workload incorrectly spread runbook

alerts/etcdNoLeader.md
This adds a basic starting runbook for `etcdNoLeader` which is a critical alert. This will be improved later on, either by etcd team or SRE folks or by feedback from our end users.
@RiRa12621 @hexfusion please take a look, as mentioned we have a lot of runbooks to add so these are just basic things and we will improve in follow ups.
=> alerts/etcdNoLeader.md: Add basic runbook

README.md
A bit of clarification on how to pass link in alerts.
Closes [MON-1738](https://issues.redhat.com/browse/MON-1738)
=> *: specify how to pass runbook link in alert

alerts/cluster-monitoring-operator/AlertmanagerFailedReload.md, alerts/cluster-monitoring-operator/KubeAPIDown.md, alerts/cluster-monitoring-operator/KubePersistentVolumeFillingUp.md, alerts/cluster-monitoring-operator/KubeletDown.md, alerts/cluster-monitoring-operator/NodeFileDescriptorLimit.md, alerts/cluster-monitoring-operator/NodeFilesystemAlmostOutOfFiles.md, alerts/cluster-monitoring-operator/NodeFilesystemAlmostOutOfSpace.md, alerts/cluster-monitoring-operator/NodeFilesystemFilesFillingUp.md, alerts/cluster-monitoring-operator/NodeFilesystemSpaceFillingUp.md, alerts/cluster-monitoring-operator/NodeRAIDDegraded.md, alerts/cluster-monitoring-operator/PrometheusTargetSyncFailure.md, alerts/cluster-monitoring-operator/ThanosRuleQueueIsDroppingAlerts.md
This adds at least a basic outline of a runbook for every critical alert shipped
by the cluster-monitoring-operator as of the OpenShift 4.9 release.  Most of
these are very incomplete, but this is a starting point.
Context: https://issues.redhat.com/browse/MON-1645
=> Add initial runbooks for all critical CMO alerts

alerts/cluster-kube-apiserver-operator/KubeAPIErrorBudgetBurn.md
this way when copy pasting, you can set the var once and the command will suceed
=> fix(KubeAPIErrorBudgetBurn): change variable name

alerts/cluster-monitoring-operator/AlertmanagerClusterFailedToSendAlerts.md, alerts/cluster-monitoring-operator/AlertmanagerFailedToSendAlerts.md
Adds two Runbooks for `AlertmanagerFailedReload` and `AlertmanagerClusterFailedToSendAlerts` alerts
=> [MON-1941]: Runbooks for FailedToSendAlerts alert

alerts/cluster-monitoring-operator/KubePersistentVolumeInodesFillingUp.md
This is a newly added alert[1] and very similar to
existing KubePersistentVolumeFillingUp but for inodes.
[1] https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/761
Signed-off-by: Arunprasad Rajkumar <arajkuma@redhat.com>
=> *: Add runbook for KubePersistentVolumeInodesFillingUp

alerts/cluster-monitoring-operator/KubeAggregatedAPIErrors.md
AggregatedAPIErrors alert was recently renamed[1] to KubeAggregatedAPIErrors.
This commit adds a runbook for the KubeAggregatedAPIErrors alert and keeps the old runbook as is to have backward compatibility.
[1] https://github.com/openshift/cluster-monitoring-operator/commit/1b85b557c8cbd4e944a5a70fbfd9f53d84218f5b
Signed-off-by: Arunprasad Rajkumar <arajkuma@redhat.com>
=> Add runbook for alert KubeAggregatedAPIErrors

alerts/cluster-etcd-operator/etcdBackendQuotaLowSpace.md, alerts/cluster-etcd-operator/etcdHighNumberOfFailedGRPCRequests.md, alerts/cluster-etcd-operator/etcdInsufficientMembers.md, alerts/cluster-etcd-operator/etcdMembersDown.md
When following the rsh step into the etcd pod I ran into an issue that was likely caused by the performance issue but it was complaining about resource "po" not existing, if "po" is replaced by "pod" it will be less confusing and prevent the suspicion of the diagnostic steps being mistaken.
Also added container selector in [etcdHighNumberOfFailedGRPCRequests.md](https://github.com/openshift/runbooks/commit/6b904166b4bbb2fea78a098326b0af3460018583#diff-8f38595acc109772fc686df2d1d664531915c14c3f72633f3757614366dfb142) as the command is receiving a label and a pod name without that option.
=> Diagnostic commands fixes for cluster-etcd-operator

alerts/cluster-kube-controller-manager-operator/GarbageCollectorSyncFailed.md, alerts/cluster-kube-controller-manager-operator/KubeControllerManagerDown.md, alerts/cluster-kube-controller-manager-operator/OWNERS, alerts/cluster-kube-controller-manager-operator/PodDisruptionBudgetAtLimit.md, alerts/cluster-kube-controller-manager-operator/PodDisruptionBudgetLimit.md
adds runbooks for following alerts:
- KubeControllerManagerDown
- PodDisruptionBudgetAtLimit
- PodDisruptionBudgetLimit
- GarbageCollectorSyncFailed
=> Bug 2001409: Introduce runbooks for kube-controller-manager-operator alerts

hack/install-markdownlint.sh
The linter currently seems a bit sad:
```
Error: Cannot find module 'node:path'
```
Some cursory research suggested this is a problem introduced in a recently-published version of markdownlint which is incompatible with nodejs 12.
This PR temporarily locks `markdownlint` and `markdownlint-cli` at a version that will work, whilst I pursue a more permanent fix in the release CI repo. At the moment, I can't fix the release CI repo because the PR rehearsals are failing for the same reason.
=> Fix linting setup

alerts/cluster-etcd-operator/etcdInsufficientMembers.md, alerts/cluster-etcd-operator/etcdNoLeader.md, alerts/cluster-monitoring-operator/NodeRAIDDegraded.md
The latest version of `markdownlint-cli2` found a few links that were
either invalid or not correctly formatted. We need to fix them before
considering upgrading the version of `markdownlint-cli2`.
Signed-off-by: Simon Pasquier <spasquie@redhat.com>
=> Fix wrong links

alerts/openshift-virtualization-operator/OWNERS
Add a subfolder for OpenShift Virtualization operator runbooks.
Signed-off-by: Shirly Radco <sradco@redhat.com>
=> Add OpenShift Virtualization operator

alerts/cluster-monitoring-operator/PrometheusRuleFailures.md
Issue: https://issues.redhat.com/browse/OCPBUGS-4219
Problem: currently there is no clear direction on how to troubleshoot the alert. This alert comes from the Prometheus repo, so improving the description there with OpenShift-specific details doesn't seem to be the best approach.
Solution: create a runbook to be linked in the OpenShift alert
=> Adds runbook for the alert PrometheusRuleFailures

alerts/cluster-network-operator/NoOvnMasterLeader.md, alerts/cluster-network-operator/NorthboundStaleAlert.md
Previous to this change, we referenced LE
API in our runbooks, but since 4.13, we now use
lease API.
Signed-off-by: Martin Kennelly <mkennell@redhat.com>
=> Migrate OVN-K specific runbooks to lease API

alerts/openshift-virtualization-operator/NodeStatusMaxImagesExceeded.md
This PR adds a runbook for the OpenShift virtualization operator `NodeStatusMaxImagesExceeded` alert
=> Add NodeStatusMaxImagesExceeded runbook

alerts/openshift-virtualization-operator/NodeStatusMaxImagesExceeded.md
To provide the user more context, a reference to the related bug is added to the runbook.
=> Reference Bug in NodeStatusMaxImagesExceeded

alerts/cluster-network-operator/OVNKubernetesControllerDisconnectedSouthboundDatabase.md
/cc @tssurya @martinkennelly @npinaeva 
Signed-off-by: Patryk Diak <pdiak@redhat.com>
=> SDN-3444: OVNKubernetesControllerDisconnectedSouthboundDatabase runbook

alerts/openshift-virtualization-operator/SSPDown.md
Currently, [SSPDown alert](https://github.com/kubevirt/ssp-operator/blob/master/internal/operands/metrics/resources.go#L82) has a runbook URL with the name SSPOperatorDown. 
This PR changes this runbook file name and headline.
Signed-off-by: assafad <aadmi@redhat.com>
=> Correct SSPDown runbook file name and headline

alerts/cluster-monitoring-operator/KubeletDown.md
SSH is useful if the kubelet is too dead to serve logs.  But in some cases like busted monitoring cert issues, the kubelet is up and the `KubeletDown` alerts are [purely monitoring-side][1]:
```console
$ oc adm node-logs --role=master -u kubelet | grep -i ' [IWE]1219' | grep -v 'I1219' | tail -n4
Dec 19 23:59:55.095722 build0-gstfj-m-2.c.openshift-ci-build-farm.internal kubenswrapper[2629]: E1219 23:59:55.095660    2629 server.go:291] "Unable to authenticate the request due to an error" err="verifying certificate SN=..., SKID=, AKID=... failed: x509: certificate signed by unknown authority"
Dec 19 23:59:55.280665 build0-gstfj-m-2.c.openshift-ci-build-farm.internal kubenswrapper[2629]: E1219 23:59:55.280603    2629 server.go:291] "Unable to authenticate the request due to an error" …
```
=> alerts/cluster-monitoring-operator/KubeletDown: Mention 'oc adm node-logs ...'

alerts/openshift-virtualization-operator/KubeVirtDeprecatedAPIRequested.md
Updating runbook name to align with [kubevirt runbook PR](https://github.com/kubevirt/kubevirt/pull/9883).
=> Update deprecated runbook api name

alerts/cluster-network-operator/OVNKubernetesNorthdInactive.md
All ocp alerts with severity critical must have a runbook associated with them. This adds the runbook for the OVN Kubernetes northd Inactive alert.
Jira link:https://issues.redhat.com/browse/SDN-3402
Signed-off-by: Ben Pickard <bpickard@redhat.com>
=> Add OVNKubernetesNorthdInactive runbook

alerts/openshift-virtualization-operator/KubemacpoolDown.md
Currently, [KubemacpoolDown alert](https://github.com/kubevirt/cluster-network-addons-operator/blob/main/data/monitoring/prom-rule.yaml#L57) has a runbook with the name `KubeMacPoolDown`. This PR fixes this.
=> Fix KubemacpoolDown runbook

alerts/openshift-container-storage-operator/CephMdsMissingReplicas.md, alerts/openshift-container-storage-operator/CephMgrIsAbsent.md, alerts/openshift-container-storage-operator/CephMgrIsMissingReplicas.md, alerts/openshift-container-storage-operator/CephMonHighNumberOfLeaderChanges.md, alerts/openshift-container-storage-operator/CephMonQuorumAtRisk.md, alerts/openshift-container-storage-operator/CephMonQuorumLost.md, alerts/openshift-container-storage-operator/CephNodeDown.md, alerts/openshift-container-storage-operator/CephOSDCriticallyFull.md, alerts/openshift-container-storage-operator/ClusterObjectStoreState.md, alerts/openshift-container-storage-operator/ObcQuotaBytesExhausedAlert.md, alerts/openshift-container-storage-operator/ObcQuotaObjectsAlert.md, alerts/openshift-container-storage-operator/ObcQuotaObjectsExhausedAlert.md, alerts/openshift-container-storage-operator/helpers/accessToolbox.md, alerts/openshift-container-storage-operator/helpers/sre-to-engineering-escalation.md
Adding runbook help for the following alerts,
CephMgrIsAbsent
CephMgrIsMissingReplicas
CephMdsMissingReplicas
CephMonQuorumAtRisk
CephMonQuorumLost
CephMonHighNumberOfLeaderChanges
CephNodeDown
CephOSDCriticallyFull
ObcQuotaObjectsAlert
ObcQuotaBytesExhausedAlert
ObcQuotaObjectsExhausedAlert
ClusterObjectStoreState
=> Add runbook help for next set of alerts

alerts/cluster-monitoring-operator/PrometheusOperatorRejectedResources.md
This PR add runbook for the alert PrometheusOperatorRejectedResources.
I have different opinion in the mitigation sections than the runbook of Prometheus Operator, which suggests the CR does not conform CRD schema. I find if the CR does not conform the schema, kubelet API server will reject before Prometheus Operator does. The error should come from the value of certain fields instead.
=> [MON-2358] add alert PrometheusOperatorRejectedResources

alerts/openshift-container-storage-operator/CephClusterReadOnly.md
The title of the document was wrong.
this alert is part of the work for RHSTOR-4979.
=> Fix CephClusterReadOnly alert title

alerts/openshift-container-storage-operator/CephMdsCpuUsageHigh.md
CephMdsCpuUsageHigh throws alert when the cpu load on mds is high. This runbook add the call to action to be taken when the alert is fired.
=> Add runbooks for CephMdsCpuUsageHigh

alerts/openshift-container-storage-operator/CephMdsCacheUsageHigh.md
Fixes:  https://bugzilla.redhat.com/show_bug.cgi?id=2256725
CephMdsCacheUsageHigh throws alert when mds cache usage exeeds 95% of the limit. This run book adds the call to action steps that can be taken when this alert is triggered in OCP.
=> Add runbooks for CephMdsCacheUsageHigh

alerts/openshift-container-storage-operator/CephMonLowNumber.md
Updated the failure zones query command for CephMonLowNumber alert to take in the count from the 'failureDomainValues' of the storagecluster
=> Update failure zones query command for CephMonLowNumber alert

alerts/openshift-container-storage-operator/CephMdsCpuUsageHigh.md
Running multiple MDS is untested. So removing it.
=> Fix runbook to remove horizontal scaling of MDS. 

alerts/openshift-container-storage-operator/CephMdsCpuUsageHigh.md
Running multiple active MDS is untested, so need to be removed.
=> Remove increase number of MDS from impact.

alerts/openshift-container-storage-operator/CephMdsCacheUsageHigh.md
Since ODF is using profiles in 4.15, it will be confusing to showw the default MDS size is 4 GB. So removing this message
=> Remove info about default MDS cache size

alerts/openshift-virtualization-operator/OWNERS
In this PR I would like to welcome @ousleyp as a reviewer and an approver for the OpenShift Virtualization operator alerts runbook.
@ousleyp is a technical writer that will help us with the effort to improve the quality of the alert runbooks.
=> Add ousleyp to owners list

alerts/openshift-container-storage-operator/CephMonQuorumAtRisk.md, alerts/openshift-container-storage-operator/CephMonQuorumLost.md
Update description of CephMonQuorumLost and CephMonQuorumAtRisk alets to consider 5 mon configurations.
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2276828
=> Update mon alerts to include 5 mon configurations

alerts/openshift-virtualization-operator/HCOInstallationIncomplete.md
Fixing an incorrect example in the HCOInstallationIncomplete runbook.
This issue was discovered in a discussion on a kubevirt/monitoring PR: https://github.com/kubevirt/monitoring/pull/240/files
I am also fixing this in the downstream docs here: https://github.com/openshift/openshift-docs/pull/75888
@machadovilaca @tiraboschi Please review this if possible and feel free to tag anyone else who should review it. Thanks!
=> [CNV] HCOInstallationIncomplete runbook fix

alerts/openshift-container-storage-operator/PersistentVolumeUsageCritical.md, alerts/openshift-container-storage-operator/PersistentVolumeUsageNearFull.md
As we are changing the alert percentages from newer ODF version onwards, making the runbooks documentation texts general, thus making runbooks not dependant on ODF versions.
=> Removing PV usage percentage numbers from runbooks doc text

alerts/openshift-container-storage-operator/CephMdsCpuUsageHigh.md
This was removed because the feature was not QA'd, now that it is, adding back the runback to horizontally scale MDS.
=> Modify MDS CPU runbook to scale mds pods.

alerts/cluster-monitoring-operator/ClusterMonitoringOperatorDeprecatedConfig.md
Related -to https://github.com/openshift/cluster-monitoring-operator/pull/2410
Since `ClusterMonitoringOperatorDeprecatedConfig` would be common for all deprecated configs it would be hard to tell in alert description whether to remove or migrate. I think it would be best to navigate to runbook
=> OCPBUGS-36495: Update alert desc in ClusterMonitoringOperatorDeprecatedConfig

.markdownlint-cli2.yaml, alerts/cluster-monitoring-operator/PrometheusOperatorRejectedResources.md
This is a first rewrite of the runbook to document the "oc get events" command as a preferred solution of "oc logs". I'll submit another PR after this one to document better the openshift-operators issue.
=> OCPBUGS-39126: update PrometheusOperatorRejectedResources.md

alerts/cluster-dns-operator/CoreDNSErrorsHigh.md, alerts/cluster-dns-operator/OWNERS
Issue: https://issues.redhat.com/browse/OCPBUGS-51193
Problem: currently there is no clear direction on how to troubleshoot the alert. This alert comes from the Prometheus repo, so improving the description there with OpenShift-specific details doesn't seem to be the best approach.
Solution: Create a runbook to be linked in the OpenShift alert
=> OCPBUGS-51193: Add runbook for CoreDNSErrorsHigh

alerts/openshift-virtualization-operator/CDIStorageProfilesIncomplete.md, alerts/openshift-virtualization-operator/KubeVirtVMIExcessiveMigrations.md, alerts/openshift-virtualization-operator/LowReadyVirtControllersCount.md, alerts/openshift-virtualization-operator/LowReadyVirtOperatorsCount.md, alerts/openshift-virtualization-operator/LowVirtAPICount.md, alerts/openshift-virtualization-operator/LowVirtControllersCount.md, alerts/openshift-virtualization-operator/LowVirtOperatorCount.md, alerts/openshift-virtualization-operator/NetworkAddonsConfigNotReady.md, alerts/openshift-virtualization-operator/NoLeadingVirtOperator.md, alerts/openshift-virtualization-operator/NoReadyVirtController.md, alerts/openshift-virtualization-operator/NoReadyVirtOperator.md, alerts/openshift-virtualization-operator/OrphanedVirtualMachineInstances.md, alerts/openshift-virtualization-operator/OutdatedVirtualMachineInstanceWorkloads.md, alerts/openshift-virtualization-operator/VirtAPIDown.md, alerts/openshift-virtualization-operator/VirtApiRESTErrorsBurst.md, alerts/openshift-virtualization-operator/VirtApiRESTErrorsHigh.md, alerts/openshift-virtualization-operator/VirtControllerDown.md, alerts/openshift-virtualization-operator/VirtControllerRESTErrorsBurst.md, alerts/openshift-virtualization-operator/VirtControllerRESTErrorsHigh.md, alerts/openshift-virtualization-operator/VirtHandlerDaemonSetRolloutFailing.md, alerts/openshift-virtualization-operator/VirtHandlerRESTErrorsBurst.md, alerts/openshift-virtualization-operator/VirtHandlerRESTErrorsHigh.md, alerts/openshift-virtualization-operator/VirtOperatorDown.md, alerts/openshift-virtualization-operator/VirtOperatorRESTErrorsBurst.md, alerts/openshift-virtualization-operator/VirtOperatorRESTErrorsHigh.md
This PR modifies several commands in the Diagnosis section of the runbooks under the Monitoring section. The current commands contain errors or deprecated syntax, leading to issues when troubleshooting. Below are the necessary modifications:
**Modifications:**
1. CDIStorageProfilesIncomplete
* Current: Identify the incomplete storage profile using: oc get storageprofile <storage_class>
* Issue: This command only shows the storage profile associated with the given storage class but does not provide details on incompleteness. To identify incomplete ones, use: oc get storageprofile -o json | jq '.items[] | select(.status.claimPropertySets == null or .status.claimPropertySets == []) | .metadata.name'
2. KubeVirtVMIExcessiveMigrations
* Current: 
* oc get nodes -l …
=> Update openshift-virtualization-operator runbook
