openshift/runbooks

alerts/AuditLogError.md
As suggested in https://github.com/openshift/cluster-kube-apiserver-operator/pull/1166
Signed-off-by: Juan Antonio Osorio Robles <jaosorior@redhat.com>
=> Add AuditLogError alert runbook

alerts/etcMemberDown.md, alerts/etcdBackendQuotaLowSpace.md
@RiRa12621 just some minor adjustments to existing runbooks, please take a look thanks.
FYI @hexfusion you might want to adjust the defrag section once your PR gets merged.
=> alerts/etcd*: Minor adjustments to existing etcd runbooks

OWNERS
=> Add ravitri as reviewer

alerts/etcdGRPCRequestsSlow.md, alerts/etcdHighFsyncDurations.md
As with others, this is some initial runbooks, and we will improve as we move forward (especially with the defrag controller feature that @hexfusion is working on this will change).
Sam, @RiRa12621 @ravitri please take a look, thanks!
=> Add initial runbooks for etcdGRPCRequestsSlow and etcdHighFsyncDurations

README.md
This PR adds an initial readme. that contains the basic set of information about this repository as well as a slim set of guidelines how to contribute
=> Readme: create initial readme

alerts/cluster-kube-apiserver-operator/KubeAPIErrorBudgetBurn.md
to KubeAPIErrorBudgetBurn runbook for copy-paste convenience
=> Add individual prometheus queries for scoped resource kinds

alerts/cluster-monitoring-operator/PrometheusTargetSyncFailure.md
found a CU who created a probe that isn't working
=> fix(PrometheusTargetSyncFailure): probe support

alerts/cluster-monitoring-operator/ThanosRuleEvaluationLatencyHigh.md
This change adds runbook for the alert `ThanosRuleEvaluationLatencyHigh`
=> Bug 2026489: add runbook for ThanosRuleEvaluationLatencyHigh Alert

alerts/cluster-monitoring-operator/ThanosRuleEvaluationLatencyHigh.md, alerts/cluster-monitoring-operator/ThanosRuleRuleEvaluationLatencyHigh.md
Fix nits mentioned in https://github.com/openshift/runbooks/pull/35
Also I renamed the file since name of alert is ThanosRuleRuleEvaluationLatencyHigh in https://github.com/openshift/cluster-monitoring-operator/blob/6fbfcbce3c5ff8a58ce3141e9d5a8fa0c7d20dae/assets/thanos-ruler/thanos-ruler-prometheus-rule.yaml#L56
=> Bug 2026489: fix nits in ThanosRuleEvaluationLatencyHigh alert

alerts/cluster-network-operator/NoRunningOvnMaster.md, alerts/cluster-network-operator/OWNERS
Signed-off-by: Martin Kennelly <mkennell@redhat.com>
/cc bmeng
/cc npinaeva
=> OVN-K: Runbook for NoRunningOvnMaster alert

alerts/cluster-network-operator/NoOvnMasterLeader.md
cc @martinkennelly 
cc @npinaeva
=> add runbook for NoOvnMasterLeader

alerts/cluster-monitoring-operator/NodeClockNotSynchronising.md
added steps to debug and start/restart the chronyd service from this SOP https://github.com/openshift/ops-sop/blob/master/v4/alerts/NodeClockNotSynchronising.md.
related card: https://issues.redhat.com/browse/OSD-8737
=> added a runbook for NodeClockNotSynchronising

alerts/cluster-etcd-operator/etcdGRPCRequestsSlow.md
=> Correcting .md of GRPC alert

alerts/cluster-network-operator/NorthboundStaleAlert.md, alerts/cluster-network-operator/SouthboundStaleAlert.md
Adding runbooks to describe northbound and southbound stale alerts in
CNO
Signed-off-by: Ben Pickard <bpickard@redhat.com>
=> Add NorthboundStale and SouthboundStale runbooks

alerts/cluster-etcd-operator/etcdHighNumberOfFailedGRPCRequests.md
=> fixing typo in etcd failed grpc request expr

alerts/cluster-etcd-operator/etcdDatabaseQuotaLowSpace.md
This PR renames etcd alert as per upstream recent changes 
see https://github.com/etcd-io/etcd/pull/14242
=> etcd: rename alert

alerts/cluster-etcd-operator/etcdInsufficientMembers.md, alerts/cluster-etcd-operator/etcdNoLeader.md
=> updated dead link to disaster recovery

alerts/cluster-etcd-operator/etcdGRPCRequestsSlow.md, alerts/cluster-etcd-operator/etcdHighFsyncDurations.md
for the update in https://github.com/openshift/cluster-etcd-operator/pull/932
=> OCPBUGS-1130: increase etcdGRPCRequestsSlow thresholds

alerts/cluster-monitoring-operator/PrometheusScrapeBodySizeLimitHit.md
This PR adds a runbook for the alert PrometheusScrapeBodySizeLimitHit that is going to be included in Openshift version 4.11 .
=> Add runbook for alert PrometheusScrapeBodySizeLimitHit

alerts/cluster-monitoring-operator/OWNERS
Signed-off-by: Jan Fajerski <jfajersk@redhat.com>
=> update CMO OWNERS

alerts/cluster-monitoring-operator/AlertmanagerFailedReload.md
=> RHDEVDOCS-4683 edit alertmanagerfailedreload runbook

alerts/cluster-monitoring-operator/AlertmanagerFailedToSendAlerts.md
Edits to the content of the runbook for consistency, grammar, and spelling
=> RHDEVDOCS-4684 - edit alertmanagerfailedtosendalerts runbook

alerts/cluster-monitoring-operator/ClusterOperatorDown.md
Style and language edits for this runbook
=> RHDEVDOCS-4686 - edit clusteroperatordown runbook

alerts/cluster-monitoring-operator/NodeFilesystemFilesFillingUp.md
Language and style edits for this runbook
=> RHDEVDOCS-4700 - edit nodefilesystemfilesfillingup runbook

alerts/cluster-monitoring-operator/NodeFilesystemAlmostOutOfFiles.md
=> RHDEVDOCS-4698 - edit nodefilesystemalmostoutoffiles runbook

alerts/cluster-monitoring-operator/KubePersistentVolumeFillingUp.md
Style and language edits for the kubepersistentvolumefillingup runbook
=> RHDEVDOCS-4692 - edit kubepersistentvolumefillingup runbook

alerts/cluster-monitoring-operator/KubeAPIDown.md
This PR edits the style and language of this runbook
=> RHDEVDOCS-4687 - edit kubeapidown runbook

alerts/cluster-monitoring-operator/ClusterOperatorDegraded.md
Language and style edits for this runbook
=> RHDEVDOCS-4685 - edit clusteroperatordegraded runbook

alerts/cluster-monitoring-operator/KubeAggregatedAPIErrors.md
Style and language edits for this runbook
=> RHDEVDOCS-4688 - edit kubeaggregatedapierrors runbook

alerts/cluster-monitoring-operator/KubeDeploymentReplicasMismatch.md
Style and language edits for this runbook.
=> RHDEVDOCS-4689-edit-kubedeploymentreplicasmismatch-runbook

alerts/cluster-monitoring-operator/KubeJobFailed.md
Style and language edits for this runbook.
=> RHDEVDOCS-4690-edit-kubejobfailed-runbook

alerts/cluster-monitoring-operator/KubeNodeNotReady.md
=> RHDEVDOCS-4691-edit-kubenodenotready-runbook

alerts/cluster-monitoring-operator/ThanosRuleRuleEvaluationLatencyHigh.md
Language and style edits for this runbook
=> RHDEVDOCS-4706-edit-thanosruleevaluationlatencyhigh-runbook

alerts/cluster-monitoring-operator/KubePersistentVolumeInodesFillingUp.md
Language and style edits for this runbook
=> RHDEVDOCS-4693-edit-kubepersistentvolumeinodesfillingup-runbook

alerts/cluster-monitoring-operator/KubePodNotReady.md
Adding language and style edits for this runbook.
=> RHDEVDOCS-4694-edit-kubepodnotready-runbook

alerts/cluster-monitoring-operator/NodeClockNotSynchronising.md
=> RHDEVDOCS-4696-edit-nodeclocknotsynchronising-runbook

alerts/cluster-monitoring-operator/NodeFilesystemSpaceFillingUp.md
=> RHDEVDOCS-4701-edit-nodefilesystemspacefillingup-runbook

alerts/cluster-monitoring-operator/PrometheusScrapeBodySizeLimitHit.md
=> RHDEVDOCS-4703-edit-prometheusscrapebodysizelimithit-runbook

alerts/openshift-virtualization-operator/CDIDataVolumeUnusualRestartCount.md
Signed-off-by: Avital Pinnick <apinnick@redhat.com>
=> CNV-22086: CDIDataVolumeUnusualRestartCount

alerts/openshift-virtualization-operator/CDIDataImportCronOutdated.md, alerts/openshift-virtualization-operator/CDIDataVolumeUnusualRestartCount.md, alerts/openshift-virtualization-operator/CnaoDown.md, alerts/openshift-virtualization-operator/KubeMacPoolDown.md, alerts/openshift-virtualization-operator/KubeVirtComponentExceedsRequestedCPU.md, alerts/openshift-virtualization-operator/KubeVirtVMIExcessiveMigrations.md, alerts/openshift-virtualization-operator/LowKVMNodesCount.md, alerts/openshift-virtualization-operator/LowVirtAPICount.md, alerts/openshift-virtualization-operator/LowVirtOperatorCount.md, alerts/openshift-virtualization-operator/NetworkAddonsConfigNotReady.md, alerts/openshift-virtualization-operator/NoReadyVirtController.md, alerts/openshift-virtualization-operator/SSPHighRateRejectedVms.md, alerts/openshift-virtualization-operator/SSPOperatorDown.md, alerts/openshift-virtualization-operator/VirtApiRESTErrorsHigh.md, alerts/openshift-virtualization-operator/VirtControllerDown.md
Fixing line breaks in files.
Signed-off-by: Avital Pinnick <apinnick@redhat.com>
=> updates and fixes

alerts/cluster-monitoring-operator/OWNERS
=> alerts/cluster-monitoring-operator: add bburt-rh to OWNERS

alerts/openshift-virtualization-operator/KubeVirtDeprecatedAPIsRequested.md
Small fixes so that Diagnosis section aligns with downstream web console.
=> Small changes to reflect web console

alerts/openshift-virtualization-operator/KubeVirtNoAvailableNodesToRunVMs.md
=> KubeVirtNoAvailableNodesToRunVMs runbook

alerts/cluster-kube-scheduler-operator/KubeSchedulerDown.md, alerts/cluster-kube-scheduler-operator/OWNERS
=> OCPBUGS-14052: Introduce runbook for kube-scheduler-operator alert

alerts/cluster-monitoring-operator/PrometheusRemoteStorageFailures.md
This PR adds a runbook for PrometheusRuleFailures alert in openshift.
=> OCPBUGS-12760: Add PrometheusRemoteStorageFailures runbook

alerts/openshift-virtualization-operator/VirtualMachineCRCErrors.md
=> CNV-30692: VirtualMachineCRCErrors runbook

alerts/cluster-monitoring-operator/OWNERS
Also move Joao to emeritus.
cc @jan--f @machine424
=> add `machine424` and `rexagod`  to OWNERS

alerts/openshift-virtualization-operator/CDIDataVolumeUnusualRestartCount.md
Fixing link format so that it is Markdown, not Asciidoc.
=> Link format fix

alerts/openshift-container-storage-operator/CephClusterErrorState.md, alerts/openshift-container-storage-operator/CephClusterWarningState.md, alerts/openshift-container-storage-operator/CephDataRecoveryTakingTooLong.md, alerts/openshift-container-storage-operator/CephMonVersionMismatch.md, alerts/openshift-container-storage-operator/CephOSDDiskNotResponding.md, alerts/openshift-container-storage-operator/CephOSDDiskUnavailable.md, alerts/openshift-container-storage-operator/CephOSDFlapping.md, alerts/openshift-container-storage-operator/CephOSDNearFull.md, alerts/openshift-container-storage-operator/CephOSDSlowOps.md, alerts/openshift-container-storage-operator/CephOSDVersionMismatch.md, alerts/openshift-container-storage-operator/CephPgRepairTakingTooLong.md, alerts/openshift-container-storage-operator/ODFPersistentVolumeMirrorStatus.md, alerts/openshift-container-storage-operator/ObcQuotaBytesAlert.md, alerts/openshift-container-storage-operator/OdfMirrorDaemonStatus.md, alerts/openshift-container-storage-operator/OdfPoolMirroringImageHealth.md, alerts/openshift-container-storage-operator/PersistentVolumeUsageNearFull.md, alerts/openshift-container-storage-operator/helpers/determineFailedOcsNode.md
this commit adds runbooks documentation for alerts related to ceph
=> add documentation for alerts related to ceph osd 

alerts/openshift-container-storage-operator/CephMonVersionMismatch.md
Fixes: 2257634
https://bugzilla.redhat.com/show_bug.cgi?id=2257634
=> Fix CephMonVersionMismatch typo an broken link

alerts/openshift-container-storage-operator/CephOSDFlapping.md
this PR fixes incorrect information in the alert documentation CephOSDFlapping
=> fix incorrect restart times in the alert documetation

alerts/openshift-container-storage-operator/CephMonLowNumber.md
Fixes: 2257634
https://bugzilla.redhat.com/show_bug.cgi?id=2257634
=> Added OCS CephMonLowNumber alert

alerts/openshift-container-storage-operator/StorageClientHeartbeatMissed.md, alerts/openshift-container-storage-operator/StorageClientIncompatibleOperatorVersion.md, alerts/openshift-container-storage-operator/helpers/connectedClient.md, alerts/openshift-container-storage-operator/helpers/verifyEndpoint.md
Adds runbook for StorageClientHearbeatMissed and StorageClientIncompatibleOperatorVersion alerts
=> Add runbooks for ODF Provider alerts

alerts/openshift-container-storage-operator/OSDCPULoadHigh.md
This PR adds the documentation for OSDCPULoadHigh alert
=> Add alert documentation for OSDCPULoadHigh alert

alerts/openshift-virtualization-operator/VMCannotBeEvicted.md
Related to the fixes in https://github.com/openshift/openshift-docs/pull/74825/
=> cnv: Fix the wording around eviction strategy

alerts/cluster-monitoring-operator/PrometheusRuleFailures.md, alerts/cluster-monitoring-operator/PrometheusTargetSyncFailure.md
from https://github.com/openshift/runbooks/pull/184#discussion_r1609980433
=> NO-JIRA: fix label selectors for some 'oc logs' commands

alerts/cluster-etcd-operator/OWNERS, alerts/cluster-etcd-operator/etcdSignerCAExpirationCritical.md
/hold
waiting for the definitive doc url
=> ETCD-586: add runbook entry for etcd-ca expiration alert

alerts/openshift-container-storage-operator/CephMdsCpuUsageHigh.md
currently if there is a horizontal scale of mds
the patch command was wrong
Corrected it using this PR
=> alert: correct mds high cpu usage patch command

alerts/cluster-monitoring-operator/PrometheusDuplicateTimestamps.md
…and add a regression note for https://issues.redhat.com/browse/OCPBUGS-39179
=> MON-4013: encourage users to consider both cases and add a regression note

alerts/machine-config-operator/MachineConfigControllerDrainError.md
Pull Request to add a new runbook for the MCCDrainError alert maintained by the MCO team.
=> MCO-88: Add runbook for MCCDrainError alert

alerts/cluster-monitoring-operator/TelemeterClientFailures.md
=> OCPBUGS-33285: Add TelemeterClientFailures runbook

alerts/cluster-image-registry-operator/ImageRegistryStorageFull.md, alerts/cluster-image-registry-operator/ImageRegistryStorageReadOnly.md
also adds appropriate directory structure since these are the first runbooks for the image registry operator.
=> IR-509: add runbooks for cluster-image-registry-operator alerts

alerts/machine-config-operator/OWNERS, alerts/machine-config-operator/SystemMemoryExceedsReservation.md
Pull Request to add a new runbook for the SystemMemoryExceedsReservation alert maintained by the MCO team.
=> MCO-1492: Add runbook SystemMemoryExceedsReservation

alerts/openshift-container-storage-operator/CephOSDDown.md
Adding runbook for ceph alert when osd is down
=> Adding runbook for ceph alert when osd is down

alerts/machine-config-operator/MachineConfigDaemonRebootError.md
Pull Request to add a new runbook for the  MCDRebootError alert maintained by the MCO team.
=> MCO-1537: Add runbook for MCDRebootError

alerts/openshift-container-storage-operator/StorageAutoScalingCapacityReached.md, alerts/openshift-container-storage-operator/StorageAutoScalingFailed.md
Adds runbook help for StorageAutoScalingCapacityReached and StorageAutoScalingFailed alerts.
=> add runbook for StorageAutoScaler alerts

alerts/machine-config-operator/ExtremelyHighIndividualControlPlaneMemory.md
Pull Request to add a new runbook for the ExtremelyHighIndividualControlPlaneMemory alert maintained by the MCO team.
=> MCO-1587: add runbook for ExtremelyHighIndividualControlPlaneMemory

alerts/openshift-container-storage-operator/StorageAutoScalingFailed.md
Diagnosis for when the error `You've reached the maximum modification rate per volume limit. Wait at least 6 hours between modifications per EBS volume` is encountered.
=> add mitigation guide for resizing error in StorageAutoScalingFailed alert

alerts/machine-config-operator/KubeletHealthState.md
Pull Request to add a new runbook for the KubeletHealthState alert maintained by the MCO team.
=> MCO-1654: Add runbook for KubeletHealthState 

alerts/cluster-monitoring-operator/AlertmanagerFailedReload.md
Improve diagnostic steps in AlertmanagerFailedReload runbook.
=> Improve diagnostic steps in AlertmanagerFailedReload runbook

alerts/machine-config-operator/MachineConfigControllerPoolAlert.md
Pull Request to add a new runbook for the MCCPoolAlert alert maintained by the MCO team.
=> MCO-1811: Add MCCPoolAlert runbook.
